### ISSUE TITLE
d-textarea does not have property max-rows

### ISSUE THREAD

**Issue by reznikartem** [DesignRevision/shards-vue#12]
First of all, thanks for your UI

## Expected Behavior
In documentation said, that d-textarea has property :max-rows for auto change textarea height.
https://designrevision.com/docs/shards-vue/components/form-textarea

## Current Behavior
In code of d-textarea component nothing about this prop :( Of course, it`s not working
https://github.com/DesignRevision/shards-vue/blob/master/src/components/form-textarea/FormTextarea.vue

**Comment by hisk** [comment]
@reznikartem Whoops! Thanks for submitting this. 😄 Expect a fix soon.

**Comment by nickvasdev** [comment]
@reznikartem I apologize for the huge delay. 😅I just released a fix.
