### ISSUE TITLE
d-nav-item and d-link won't work with named routes

### ISSUE THREAD

**Issue by St3Ko** [DesignRevision/shards-vue#4]
first of all, thank you very much for this awesome ui kit!

## Expected Behavior
the :to prop for d-nav-item and d-link should work like the same way router-link :to does.
[how they should work](https://router.vuejs.org/guide/essentials/named-routes.html)

## Current Behavior
d-nav-item and d-link :to prop only accepts a string or an object with a path prop

## Steps to Reproduce
1. use a d-nav-item or d-link with a named route
2. will produce href="#"

## Context (Environment)

i mainly use named routes in my apps so this would be awesome if it would work

**Comment by hisk** [comment]
@St3Ko Thanks for taking the time to submit this Stefan! 😊I just noticed a major improper binding for the `<d-link>` component that caused this bug. I just submitted a fix for it and updated the package.

Please update to `1.0.2` and let me know how it goes.

**Comment by St3Ko** [comment]
Works like a charm now :) Thank you very much for this fast fix!
